name: Bug report
description: Empty issue with defaults for bug reports
title: "[bug] "
labels: ["bug"]
assignees: devlsh
body:
  - type: textarea
    attributes:
      label: Bug description
    validations:
      required: false
